library(ggplot2)
library(ggmap)
library(rworldmap)
library(magrittr)
library(reshape)
library(Rmisc)
library(geosphere)

ll <- read.table("Data/LatLongAllPops.txt",header = F)
admix3 <- read.table("Data/HapMapMajorPruned.3.Q")
admix6 <- read.table("Data/HapMapMajorPruned.6.Q")
pops <- read.table("Data/HapMapMajorPruned.fam",stringsAsFactors = F)
p_markers <- read.table("Data/HapMapMajorPruned.bim",stringsAsFactors = F)
markers <- read.table("Data/HapMapMajor.bim",stringsAsFactors = F)
pd <- read.table("Data/PairwiseFST.txt",stringsAsFactors = F)
het <- read.table("Data/PopHet.txt",header = T)
ld <- read.table("Data/LD.txt",header = F)
